# Generated by Django 2.0 on 2018-11-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name of Events')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Description')),
                ('max_slot', models.IntegerField(blank=True, null=True, verbose_name='Max Slots')),
                ('date_from', models.DateField(verbose_name='Start Date')),
                ('date_to', models.DateField(verbose_name='End Date')),
                ('time_from', models.TimeField(verbose_name='Start Time')),
                ('time_to', models.TimeField(verbose_name='End Time')),
                ('venue', models.CharField(max_length=100, verbose_name='Venue')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
        ),
    ]
